### PR TITLE
fix(code-viewer): line numbers are incorrect in certain cases

### PR DESCRIPTION
**Pull request by P0lip**
Fixes https://github.com/stoplightio/platform-internal/pull/3852#issuecomment-669169794

### CODE REVIEW

**Comment by wmhilton** [comment]
> Fixes [stoplightio/platform-internal#3852 (comment)](https://github.com/stoplightio/platform-internal/pull/3852#issuecomment-669169794)

You said the same thing in https://github.com/stoplightio/ui-kit/pull/184

**Comment by P0lip** [comment]
@wmhilton 
no, the first PR fixed the problem with padding/spacing (the first comment), while this one fixes the incorrect number lines (the second comment you posted)

**Comment by wmhilton** [comment]
Ah. So you meant 

> Fixes (part of) [stoplightio/platform-internal#3852 (comment)](https://github.com/stoplightio/platform-internal/pull/3852#issuecomment-669169794)

both times?

**Comment by P0lip** [comment]
the first PR fixed the padding issue in CodeEditor, while this one fixes the wrong lines number in CodeViewer

**Pull request merged**
