### PR TITLE
chore: storybook v5

### PR DESCRIPTION
**Pull request by P0lip**

### CODE REVIEW

**Comment by wmhilton** [comment]
why has this sat here for 9 days?

correction: why has Pull Reminders never notified me about this?

**Comment by wmhilton** [comment]
this looks off:
image

**Comment by wmhilton** [comment]
maybe a similar problem?
image

**Comment by P0lip** [comment]
@wmhilton 
Ah, it's not ready yet, therefore I didn't add anyone as a reviewer.
It should be marked as draft.
I'll try to address the comments soon + fix all the issues (lack of dark theme and broken navigation).

**Comment by wmhilton** [comment]
Weird... some reason I thought like four people were added as reviewers (myself included)? Maybe I was just mixing things up. (Or maybe GitHub really did show me that.)

**Comment by P0lip** [comment]
@wmhilton
Implemented all the needed changes.
 
requires https://github.com/stoplightio/storybook-config/pull/8

https://github.com/stoplightio/ui-kit/pull/90#issuecomment-478142160
It happens on master as well - I suppose it's a regression caused by spacing adjustments.
I will fix it.

**Comment by wmhilton** [comment]
Also, @P0lip you still have storybook-config yalc'ed.

**Comment by P0lip** [comment]
Yeah, see my comment above.
I need https://github.com/stoplightio/storybook-config/pull/8 to land.

**Comment by wmhilton** [comment]
I'll approve https://github.com/stoplightio/storybook-config/pull/8 when this PR is working. 👍

**Comment by P0lip** [comment]
@wmhilton 
Fixed everything!

**Comment by wmhilton** [comment]
Is the "theme" getting passed to Popup correctly?

# Light
image

# Dark
image

**Pull request merged**
