### PR TITLE
feat: move TableOfContents from platform

### PR DESCRIPTION
**Pull request by marcelltoth**
Will resolve stoplightio/platform-internal#2219

### CODE REVIEW

**Comment by marcelltoth** [comment]
I'm `yalc`ing but platform wouldn't even launch normally. :\

**Comment by marcelltoth** [comment]
1. done ✔️ 
image

2. I have tweaked the storybook in my initial commit already. It is working.

3. Can't comment on this.

**Comment by XVincentX** [comment]
@lottamus What do you think

**Comment by marcelltoth** [comment]
Don't merge this, something's not 100% right just yet. Even if I updated elements to work with the new ToC, the directories are not clickable for some reason
image

**Comment by marcelltoth** [comment]
I fixed the outstanding bug, can this get merged now? @XVincentX @lottamus

**Pull request merged**
